# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
AMAZON_KEY: AKIAJ4ZF2OGURAAHVGDQ
AMAZON_SECRET: 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

GMAIL_USERNAME: ratafire@ratafire.com
GMAIL_PASSWORD: youshallnotpass

FACEBOOK_KEY: 249146721904203
FACEBOOK_SECRET: 7314060e069b3db3977fdc5de2a12fa1

TWITTER_KEY: MjqYvbCBAYaZVTTddDDNQ
TWITTER_SECRET: KQti1l9dKUD31QFuFA1CApcoFIopsDSWixSR1iKjP0

GITHUB_KEY: 18ed1fa2bc9ab8d56695
GITHUB_SECRET: eddbce4335a045ba0a25d47963efc9c3255ce826

DEVIANTART_KEY: 1134
DEVIANTART_SECRET: 1a78f1c0b7dce44c2082169bfcfcc67d

VIMEO_KEY: dfef82c16a58e709ec5f9916f3ecdf35c93e5f30
VIMEO_SECRET: eda766229b43563482bce0a7315677264b0140aa

ZENCODER_API_KEY: 8fa049ee1d0050ea8bd520d085f128a9
ZENCODER_NOTIFICATION: https://www.ratafire.com/videos/notification/r/encode_notify

GOOGLE_ANALYTICS: UA-13007947-7
