# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
AMAZON_KEY: AKIAJ4ZF2OGURAAHVGDQ
AMAZON_SECRET: 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

GMAIL_USERNAME: ratafire@ratafire.com
GMAIL_PASSWORD: youshallnotpass

ZENCODER_API_KEY: 8fa049ee1d0050ea8bd520d085f128a9