# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
AMAZON_KEY: AKIAJ4ZF2OGURAAHVGDQ
AMAZON_SECRET: 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

AMAZON_MWS_KEY: AKIAIRIRMU6DK75ZW6ZA
AMAZON_MWS_SECRET: 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

AMAZON_CLIENT_ID: amzn1.application-oa2-client.d456fd3b4a144d1b8cfa69d2f80d7063
AMAZON_CLIENT_SECRET: 5941f979c9e2ce4aa33dd70b9fb3e6917298bb160ef812247269b1324da31068

AMAZON_MERCHENT_ID: A35J8GZRKDHSLN

GMAIL_USERNAME: ratafire@ratafire.com
GMAIL_PASSWORD: youshallnotpass

FACEBOOK_KEY: 249146721904203
FACEBOOK_SECRET: 7314060e069b3db3977fdc5de2a12fa1

FACEBOOK_KEY_TEST: 368036150015259
FACEBOOK_SECRET_TEST: 0887049870d71f3faca369f457788a69

TWITTER_KEY: MjqYvbCBAYaZVTTddDDNQ
TWITTER_SECRET: KQti1l9dKUD31QFuFA1CApcoFIopsDSWixSR1iKjP0

GITHUB_KEY: 18ed1fa2bc9ab8d56695
GITHUB_SECRET: eddbce4335a045ba0a25d47963efc9c3255ce826

DEVIANTART_KEY: 1134
DEVIANTART_SECRET: 1a78f1c0b7dce44c2082169bfcfcc67d

VIMEO_KEY: dfef82c16a58e709ec5f9916f3ecdf35c93e5f30
VIMEO_SECRET: eda766229b43563482bce0a7315677264b0140aa

ZENCODER_API_KEY: 8fa049ee1d0050ea8bd520d085f128a9
ZENCODER_NOTIFICATION: https://www.ratafire.com/videos/notification/r/encode_notify

GOOGLE_ANALYTICS: UA-13007947-7

PRICE_1: 2.49
PRICE_1_RECEIVE: 1.87
PRICE_2: 9.00
PRICE_2_RECEIVE: 8.19
PRICE_3: 14.99
PRICE_3_RECEIVE: 14.01
PRICE_4: 24.00
PRICE_4_RECEIVE: 22.75
PRICE_5: 49.00
PRICE_5_RECEIVE: 47.03
PRICE_6: 99.00
PRICE_6_RECEIVE: 95.58

TIMEBOMB_COUNT: 3
TIMEBOMB_DAYS: 15

SENDGRID_USERNAME: ratafire
SENDGRID_PASSWORD: youarebeingwatched2018

SOUNDCLOUD_CLIENT_ID: cc6a5434aec089a49d3fbc0c69530880
SOUNDCLOUD_CLIENT_SECRET: 9f4f6670dd39b173c876d7de8f4a371c

SLOGAN: Cloud Patronage

PAYPAL_USERNAME: paypal_api1.ratafire.com
PAYPAL_PASSWORD: D32PHUYV86CCHXBZ
PAYPAL_SIGNATURE: AiPC9BjkCyDFQXbSkoZcgqH3hpacAyyafoEkPkvGs6daNRbK-k9nWg2e
PAYPAL_SANDBOX_ID: APP-80W284485P519543T

PAYPAL_SANDBOX_CLIENT_ID: AToRZkRVMGGxuNMmypMmQiJN8dTEyGXrN7Kr8SC3SdkLNh16qfCbaCj3DbEaqkJsxG4U4MBJufxc2lZJ
PAYPAL_SANDBOX_CLIENT_SECRET: ELYr3VOscSscypDVsM3A9k3TiyfpDppAQYeORpDzAoZWwgwNxmjR1cvYEKXutBIbOBSTCG6tHQtvbvpj
PAYPAL_SANDBOX_USERNAME: paypal-facilitator@ratafire.com
PAYPAL_SANDBOX_PASSWORD: happynewyear1234
PAYPAL_SANDBOX_SIGNATURE: AvigQk98pmsZuOmn9o2jUgUI9wHvAn20GS1qNYUTjZYCTf9kh2Xwgi4m

STRIPE_PUBLIC_KEY: pk_live_qYBcFpw1hpehDe5UPjywIkJk
STRIPE_SECRET_KEY: sk_live_OfXha6zXdAHdTcIISPQpZt8V

STRIPE_TEST_PUBLIC_KEY: pk_test_QTy54pPL2PSQLbW2l5hC51uW
STRIPE_TEST_SECRET_KEY: sk_test_bwcG9rsbMaJHQC41Fz4J1iU5
