
# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
APPLICATION_VERSION: "3.0.0"

AMAZON_KEY: AKIAJ4ZF2OGURAAHVGDQ
AMAZON_SECRET: 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

AMAZON_MWS_KEY: AKIAIRIRMU6DK75ZW6ZA
AMAZON_MWS_SECRET: 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

AMAZON_CLIENT_ID: amzn1.application-oa2-client.d456fd3b4a144d1b8cfa69d2f80d7063
AMAZON_CLIENT_SECRET: 5941f979c9e2ce4aa33dd70b9fb3e6917298bb160ef812247269b1324da31068

AMAZON_MERCHENT_ID: A35J8GZRKDHSLN

GOOGLE_CLIENT_ID: 285175062966-472n7g5m7boqa8i8vruigpqtipc12oc9.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: 9_PaZsiDHIM5LsFeqIHzfnNk

PINTEREST_APP_ID: "4820643734515361807"
PINTEREST_APP_SECRET: 2c4aaa8df3795c667d4da34a08c779be54efe66f0ff70ca00a087ca9e95e258d

TWITCH_CLIENT_ID: 1wt36nl57kjw8m7zskxfoat8v7kchpl
TWITCH_CLIENT_SECRET: 82cuikn5t8r5hr5dsxht0d0q2fsx33g

GMAIL_USERNAME: ratafire@ratafire.com
GMAIL_PASSWORD: youshallnotpass

FACEBOOK_KEY: "249146721904203"
FACEBOOK_SECRET: 7314060e069b3db3977fdc5de2a12fa1

FACEBOOK_KEY_TEST: "368036150015259"
FACEBOOK_SECRET_TEST: 0887049870d71f3faca369f457788a69

TWITTER_KEY: MjqYvbCBAYaZVTTddDDNQ
TWITTER_SECRET: KQti1l9dKUD31QFuFA1CApcoFIopsDSWixSR1iKjP0

GITHUB_KEY: 18ed1fa2bc9ab8d56695
GITHUB_SECRET: eddbce4335a045ba0a25d47963efc9c3255ce826

DEVIANTART_KEY: "1134"
DEVIANTART_SECRET: 1a78f1c0b7dce44c2082169bfcfcc67d

VIMEO_KEY: dfef82c16a58e709ec5f9916f3ecdf35c93e5f30
VIMEO_SECRET: eda766229b43563482bce0a7315677264b0140aa

ZENCODER_API_KEY: 8fa049ee1d0050ea8bd520d085f128a9
ZENCODER_NOTIFICATION: https://ratafire.com/video/zencoder_notify_encode

GOOGLE_ANALYTICS: UA-13007947-7

SENDGRID_USERNAME: ratafire
SENDGRID_PASSWORD: youarebeingwatched2018

SOUNDCLOUD_CLIENT_ID: cc6a5434aec089a49d3fbc0c69530880
SOUNDCLOUD_CLIENT_SECRET: 9f4f6670dd39b173c876d7de8f4a371c

SLOGAN: We help artists and researchers afford the time for creative freedom

PAYPAL_USERNAME: paypal_api1.ratafire.com
PAYPAL_PASSWORD: D32PHUYV86CCHXBZ
PAYPAL_SIGNATURE: AiPC9BjkCyDFQXbSkoZcgqH3hpacAyyafoEkPkvGs6daNRbK-k9nWg2e
PAYPAL_CLIENT_ID: AbmzMPO6vNkeHOIomMlOc-z0okktJzfFR3kFDrCPYr9_pWaKA7GQeI0ZRdjtJysR5kIgPrWIgDfGSPMv
PAYPAL_CLIENT_SECRET: EIcuAqGe3ad7M1zOBY7SmjNvOmzED3EqOiaBMmD0EiuCY3bd6N5gXT6ED47qjCgLaOVk5XQ8clfRrVRA

PAYPAL_SANDBOX_ID: APP-80W284485P519543T
PAYPAL_SANDBOX_CLIENT_ID: AToRZkRVMGGxuNMmypMmQiJN8dTEyGXrN7Kr8SC3SdkLNh16qfCbaCj3DbEaqkJsxG4U4MBJufxc2lZJ
PAYPAL_SANDBOX_CLIENT_SECRET: ELYr3VOscSscypDVsM3A9k3TiyfpDppAQYeORpDzAoZWwgwNxmjR1cvYEKXutBIbOBSTCG6tHQtvbvpj
PAYPAL_SANDBOX_USERNAME: paypal-facilitator_api1.ratafire.com
PAYPAL_SANDBOX_PASSWORD: JPNM2USSNDPFPEUM
PAYPAL_SANDBOX_SIGNATURE: AvigQk98pmsZuOmn9o2jUgUI9wHvAn20GS1qNYUTjZYCTf9kh2Xwgi4m

PAYPAL_MASSPAY_TRANSACTION_LIMIT: "10000"
PAYPAL_MASSPAY_BATCH_LIMIT: "250"

STRIPE_PUBLIC_KEY: pk_live_qYBcFpw1hpehDe5UPjywIkJk
STRIPE_SECRET_KEY: sk_live_OfXha6zXdAHdTcIISPQpZt8V

STRIPE_TEST_PUBLIC_KEY: pk_test_QTy54pPL2PSQLbW2l5hC51uW
STRIPE_TEST_SECRET_KEY: sk_test_bwcG9rsbMaJHQC41Fz4J1iU5

STRIPE_WEBHOOK_SECRET: 26d63d11f80a7c18b3454c4a540018e2

VENMO_CLIENT_ID: "2540"
VENMO_CLIENT_SECRET: qpX3LBcmYvrP2ygz8P3EKWbmsZwNvZp2

VENMO_SANDBOX_CLIENT_ID: "2544"
VENMO_SANDBOX_CLIENT_SECRET: ScALSwuVVWYXyBeMtgN7FyRKZk6ALHpy

VENMO_ACCESS_TOKEN: 984879bee38c1abcd7fa59f4293a0ab6b304a600b89a497f23bd050191997820

ADMIN_EMAIL: fariliang@ratafire.com

SSN_KEY: p(\xFA\v8~\xA8\xBE\xAF\xA9\xE2\x16)\xF2\xD4\x1CV\xE8\xC1\xAD\xF5\x81A\xAFA\x0E`\x9C\xE7\xCA\xD7u
ID_CARD_KEY: \xA3\xA6\xC9\xFE\xAFo\a\xE2<\xBC\xAE\t-\x89\xBA\x12\x144o\x13\xEEf\xBF\xBCY\xE9M\xD0\x15R\xCC\x00
PASSPORT_KEY: \xE68@\xD8\x02A\x8E\xF2|\x15?\xA6\xD7\xDC\xC0\xD0_EsS].7\xF6\xD5\xAF\xBA\xC0\x9Bo6E
ACCOUNT_NUMBER_KEY: A\xD3\xF8\x89\x06O>\xED\x004\xD3\xCC\xA3\xB4\x16\x004\xF84\xE8\xF1\x9B\x84\xD5Q\x87=\xD2\x13X\xAA\b
ROUTING_NUMBER_KEY: CJ\x87\xC0I`\xCA\xC7\x01\xAFJ{\xF3\xD4\x95\xFC\xECN\xF7\xD2\xE2\xE7\r\x1D\x16:\\\"\x11iG5
POSTAL_CODE_KEY: \xF3\x12\x03\vySH)0\x16\xED\xD9\x1Ex\xB1\xB1\xCE\xAA6(\x90.\xA6WBm\x19T\x85a\x99\xA5
CARD_NUMBER_KEY: \xF4\xC6W\x8BHf\x04\x1E8\x11\x0E\b\x9F\x01\xBA\x8E\xAD\x1D\xE7X\xE1\xED^\x1C\xA7\xD6\xEA\xDDY\x888\xD6
EXP_MONTH_KEY: \x81\xA5\xB1\xAF\xA1\xCB\x8Dw3\xDEm+ \xB8)\xBD'sya\xF7\e\xA5-=\xDE\xDBH$\xB24?
EXP_YEAR_KEY: \xA6tUE\x87\xE4\xBA\xA9\a\aD\x16\x81mM\xF5H\xA4 tvd\x05\xE9[\xDEI\xB2'V\xE5i
CVC_KEY: Y9|{\xA9\x0F\xEC\bz)l\xDC\x94\xEB\xCD\x96\xA8o \r\xD4\r-\xB7qN\x1D-\x97H\x9D~
ADDRESS_ZIP_KEY: h\xAA\x87\xE0Q\xBF/\x92\x88.A\xEA\x16\x9FT\xBC\x0F\xC5f2\xEFk\xA95\x06\xEF\x9Fs*q\xDA\xF7