development:
  adapter: postgresql
  database: ratafire_development
  pool: 5
  timeout: 5000
  username: fari

production:
  adapter: postgresql
  database: ratafire_production
  pool: 5
  timeout: 5000