monthly_subscriptions:
  cron: "* * * * *"
  custom_job_class: "SubscriptionWorker"
  queue: subscriptions_queue
  args:
  description: "This worker queues subscription fee transactions."
test_schedule:
  cron: "* * * * *"
  custom_job_class: "TestWorker"
  queue: test_queue
  args:
  description: "This worker queues subscription fee transactions."  