s3_output:
  bucket: Ratafire_production_videos_encoded
  access_key_id: AKIAJ4ZF2OGURAAHVGDQ
  secret_access_key: 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
settings:
  notification_url: http://zencoderfetcher/videos/encode_notify